# Generated by Django 3.2.2 on 2021-10-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('animation', 'Animation'), ('biography', 'Biography'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('documentary', 'Documentary'), ('drama', 'Drama'), ('family', 'Family'), ('fantasy', 'Fantasy'), ('history', 'History'), ('horror', 'Horror'), ('music', 'Music'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('short', 'Short'), ('thriller', 'Thriller'), ('war', 'War'), ('western', 'Western')], help_text='Please a movie genre', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please add a language', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name of the person', max_length=100)),
                ('last_name', models.CharField(help_text='Enter last name of the person', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_title', models.CharField(max_length=2000, unique=True)),
                ('release_date', models.DateField(verbose_name='Date released')),
                ('tagline', models.CharField(max_length=100)),
                ('overview', models.TextField(help_text='Please enter a brief description for this movie', max_length=1000)),
                ('poster_path', models.CharField(max_length=100)),
                ('length', models.TimeField()),
                ('cast', models.ManyToManyField(related_name='cast', to='movies.Person')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directors', to='movies.person')),
                ('genres', models.ManyToManyField(to='movies.Genre')),
                ('language', models.ForeignKey(default='en', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.language')),
            ],
        ),
    ]
